version: "3.9"
services:
  worker:
    build:
      context: "."
    depends_on:
      - postgres
    env_file: .env

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: data
      POSTGRES_PASSWORD: PASSWORD5432
    ports:
      - 5433:5432
