name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'

    - name: Install npm 7
      run: npm i -g npm

    - name: Install TypeScript compiler
      run: npm i typescript@`node -p -e "(require('./package.json').devDependencies.typescript).slice(1)"`

    - name: Build App
      run: npm run build --if-present

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag redstripez08/calnatsci-ts:$(date +%s)
